import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import Container from "@/components/container";
import Navbar from "@/components/layer/navbar";

const gilmer = localFont({
  preload: true,
  src: [
    {
      path: "../../public/fonts/Gilmer-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Gilmer-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Gilmer-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Gilmer-Heavy.woff2",
      weight: "800",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${gilmer.className} antialiased`}
    >
      <body className="overflow-x-hidden bg-bg-primary-default text-base font-normal text-text-primary-default">
        <Container>
          <Navbar />
        </Container>
        {children}
      </body>
    </html>
  );
}
